In [2]:
import nltk.data
import pandas as pd
import pickle
import datetime
from sklearn.cross_validation import StratifiedKFold
import numpy as np

In [3]:
# Load the punkt tokenizer
tokenizer = nltk.data.load('tokenizers/punkt/english.pickle')

### movie_reviews

In [4]:
# Read data from files
df = pd.read_csv( 'labeledTrainData.tsv', header=0, delimiter="\t", quoting=3 )
unlabeled_train = pd.read_csv( "unlabeledTrainData.tsv", header=0,  delimiter="\t", quoting=3)

In [5]:
df[0:10]

id  sentiment                                             review
0   "5814_8"          1  "With all this stuff going down at the moment ...
1   "2381_9"          1  "\"The Classic War of the Worlds\" by Timothy ...
2   "7759_3"          0  "The film starts with a manager (Nicholas Bell...
3   "3630_4"          0  "It must be assumed that those who praised thi...
4   "9495_8"          1  "Superbly trashy and wondrously unpretentious ...
5   "8196_8"          1  "I dont know why people think this is such a b...
6   "7166_2"          0  "This movie could have been very good, but com...
7  "10633_1"          0  "I watched this video at a friend's house. I'm...
8    "319_1"          0  "A friend of mine bought this film for £1, and...
9  "8713_10"          1  "<br /><br />This movie is full of references....

In [6]:
df.columns = ['id', 'boolean_label', 'abstract']

### confirmed that different indices are being selected by the CV method by comparing two runs of the same code below

In [7]:
a = datetime.datetime.now().replace(microsecond=0)

y = df['boolean_label'].values

trainIndices = []
testIndices = []

for k in range(25):

    inxTrain = []
    inxTest = []
    #set random state
    skf = StratifiedKFold(y, n_folds=5, shuffle=True)

    for train_index, test_index in skf:

        #print(train_index)
        #print(test_index)
        #print("----------")
        inxTrain.append(train_index)
        inxTest.append(test_index)
        
    trainIndices.append(inxTrain)
    testIndices.append(inxTest)
                        
b = datetime.datetime.now().replace(microsecond=0)
print(b-a)

0:00:01


In [8]:
len(trainIndices[0])
#len(testIndices)

5

In [22]:
df.iloc[trainIndices[0][1]]

id  boolean_label  \
1        "2381_9"              1   
2        "7759_3"              0   
3        "3630_4"              0   
5        "8196_8"              1   
6        "7166_2"              0   
7       "10633_1"              0   
8         "319_1"              0   
9       "8713_10"              1   
10       "2486_3"              0   
11      "6811_10"              1   
12      "11744_9"              1   
13       "7369_1"              0   
14      "12081_1"              0   
15       "3561_4"              0   
16       "4489_1"              0   
17       "3951_2"              0   
19      "9352_10"              1   
21      "10782_7"              1   
22      "5414_10"              1   
23      "10492_1"              0   
24       "3350_3"              0   
25       "6581_7"              1   
26       "2203_3"              0   
27        "689_1"              0   
28       "9152_1"              0   
29       "6077_1"              0   
31       "9727_7"              1   
32       "1297_8"              1   
33       "5586_8"              1   
34       "1119_1"              0   
...           ...            ...   
24961    "9280_9"              1   
24962    "2041_2"              0   
24964    "7532_4"              0   
24966    "1184_3"              0   
24967    "7061_1"              0   
24968    "3402_2"              0   
24969  "11416_10"              1   
24970    "9389_7"              1   
24971    "9251_9"              1   
24972   "1422_10"              1   
24974    "7492_7"              1   
24975   "7689_10"              1   
24976   "12370_4"              0   
24977    "5625_8"              1   
24978    "9397_9"              1   
24979    "5992_7"              1   
24981   "9627_10"              1   
24982    "3822_2"              0   
24983    "5983_4"              0   
24984    "8021_2"              0   
24986   "6034_10"              1   
24987    "1988_9"              1   
24988    "7623_9"              1   
24989    "5974_7"              1   
24991    "9416_3"              0   
24992   "10994_1"              0   
24993   "10957_3"              0   
24995    "3453_3"              0   
24997   "10905_3"              0   
24999    "8478_8"              1   

                                                abstract  
1      "\"The Classic War of the Worlds\" by Timothy ...  
2      "The film starts with a manager (Nicholas Bell...  
3      "It must be assumed that those who praised thi...  
5      "I dont know why people think this is such a b...  
6      "This movie could have been very good, but com...  
7      "I watched this video at a friend's house. I'm...  
8      "A friend of mine bought this film for £1, and...  
9      "<br /><br />This movie is full of references....  
10     "What happens when an army of wetbacks, towelh...  
11     "Although I generally do not like remakes beli...  
12     "\"Mr. Harvey Lights a Candle\" is anchored by...  
13     "I had a feeling that after \"Submerged\", thi...  
14     "note to George Litman, and others: the Myster...  
15     "Stephen King adaptation (scripted by King him...  
16     "`The Matrix' was an exciting summer blockbust...  
17     "Ulli Lommel's 1980 film 'The Boogey Man' is n...  
19     "Most people, especially young people, may not...  
21     "Michael Stearns plays Mike, a sexually frustr...  
22     "This happy-go-luck 1939 military swashbuckler...  
23     "I would love to have that two hours of my lif...  
24     "The script for this movie was probably found ...  
25     "Looking for Quo Vadis at my local video store...  
26     "Note to all mad scientists everywhere: if you...  
27     "What the ........... is this ? This must, wit...  
28     "Intrigued by the synopsis (every gay video th...  
29     "Would anyone really watch this RUBBISH if it ...  
31     "Simon Pegg plays a rude crude and often out o...  
32     "Faithful adaptation of witty and interesting ...  
33     "Eva (Hedy Lamarr) has just got married with a...  
34     "Even

In [71]:
pickle.dump(trainIndices, open('/mnt/mypartition/PAPER/trainIndicesMR.p', 'wb'))

In [72]:
pickle.dump(testIndices, open('/mnt/mypartition/PAPER/testIndicesMR.p', 'wb'))

### Amazon fine food reviews

In [4]:
df = pd.read_csv('Reviews.csv')

In [43]:
df['Text'].loc[0]

'I have bought several of the Vitality canned dog food products and have found them all to be of good quality. The product looks more like a stew than a processed meat and it smells better. My Labrador is finicky and she appreciates this product better than  most.'

In [5]:
df.columns = ['Id', 'ProductId', 'UserId', "ProfileName", 'HelpfulnessNumerator', 'HelpfulnessDenominator', 'label', 'Time', 'title', 'abstract']

In [45]:
df[0:2]

Id   ProductId          UserId ProfileName  HelpfulnessNumerator  \
0   1  B001E4KFG0  A3SGXH7AUHU8GW  delmartian                     1   
1   2  B00813GRG4  A1D87F6ZCVE5NK      dll pa                     0   

   HelpfulnessDenominator  label        Time                  title  \
0                       1      5  1303862400  Good Quality Dog Food   
1                       0      1  1346976000      Not as Advertised   

                                            abstract  
0  I have bought several of the Vitality canned d...  
1  Product arrived labeled as Jumbo Salted Peanut...

In [6]:
#randomly subset those with label 5 to be more similar to actual amount (*** and most importantly to reduce size of dataset)
df_5 = df.loc[df['label'] == 5]
df_5 = df_5.sample(n=50000, random_state=10)

In [10]:
print(df_5['Id'])

459791    459792
87685      87686
114816    114817
69163      69164
403978    403979
489490    489491
16699      16700
167783    167784
3031        3032
123399    123400
18678      18679
308376    308377
477631    477632
208595    208596
318447    318448
566580    566581
139461    139462
368180    368181
46761      46762
51156      51157
425272    425273
94097      94098
378813    378814
117134    117135
255187    255188
175663    175664
378800    378801
468850    468851
283333    283334
218783    218784
           ...  
360349    360350
256097    256098
100767    100768
166940    166941
210771    210772
170471    170472
176188    176189
527239    527240
471804    471805
529558    529559
275867    275868
473884    473885
421308    421309
382277    382278
551521    551522
289265    289266
298675    298676
261497    261498
187481    187482
71664      71665
509082    509083
223115    223116
538357    538358
477887    477888
376105    376106
318347    318348
105912    105913
524759    5247

In [49]:
df_allElse = df.loc[df['label'] != 5]
df = pd.concat([df_allElse, df_5])

In [56]:
a = datetime.datetime.now().replace(microsecond=0)

y = df['label'].values

trainIndices = []
testIndices = []

for k in range(25):

    inxTrain = []
    inxTest = []
    #set random state
    skf = StratifiedKFold(y, n_folds=5, shuffle=True)

    for train_index, test_index in skf:

        #print(train_index)
        #print(test_index)
        #print("----------")
        inxTrain.append(train_index)
        inxTest.append(test_index)
        
    trainIndices.append(inxTrain)
    testIndices.append(inxTest)
                        
b = datetime.datetime.now().replace(microsecond=0)
print(b-a)

0:00:02


In [60]:
len(trainIndices[24])
#len(testIndices)

5

In [61]:
pickle.dump(trainIndices, open('/mnt/mypartition/PAPER/trainIndicesAFFR.p', 'wb'))

In [62]:
pickle.dump(testIndices, open('/mnt/mypartition/PAPER/testIndicesAFFR.p', 'wb'))

### Twitter dataset

In [5]:
#df=pd.read_csv('sentiment_analysis_twitter_full.csv', header=0, sep=',', error_bad_lines=False)
df=pd.read_csv('subset100000.csv', header=0, sep=',', error_bad_lines=False)

In [6]:
df.columns = ['id', 'boolean_label', 'sentiment_source', 'abstract']

In [7]:
a = datetime.datetime.now().replace(microsecond=0)

y = df['boolean_label'].values

trainIndices = []
testIndices = []

for k in range(25):

    inxTrain = []
    inxTest = []
    #set random state
    skf = StratifiedKFold(y, n_folds=5, shuffle=True)

    for train_index, test_index in skf:

        inxTrain.append(train_index)
        inxTest.append(test_index)
        
    trainIndices.append(inxTrain)
    testIndices.append(inxTest)
                        
b = datetime.datetime.now().replace(microsecond=0)
print(b-a)

0:00:01


In [8]:
trainIndices[0]

[array([    0,     1,     2, ..., 99996, 99997, 99998]),
 array([    0,     1,     3, ..., 99995, 99996, 99997]),
 array([    0,     1,     2, ..., 99994, 99996, 99998]),
 array([    2,     3,     4, ..., 99995, 99997, 99998]),
 array([    0,     1,     2, ..., 99996, 99997, 99998])]

In [9]:
testIndices[0]

[array([    6,    10,    12, ..., 99980, 99992, 99993]),
 array([    2,     9,    11, ..., 99979, 99987, 99998]),
 array([    3,     4,    20, ..., 99990, 99995, 99997]),
 array([    0,     1,     5, ..., 99986, 99994, 99996]),
 array([   26,    32,    40, ..., 99967, 99977, 99991])]

In [10]:
len(trainIndices[0][0])

79998

In [11]:
len(testIndices[0][0])

20001

In [13]:
pickle.dump(trainIndices, open('/mnt/mypartition/paper_final_code/trainIndicesTSAsub.p', 'wb'))

In [12]:
pickle.dump(testIndices, open('/mnt/mypartition/paper_final_code/testIndicesTSAsub.p', 'wb'))